### ISSUE TITLE
TypeError: Cannot read property '_setChildrenPayload'

### ISSUE THREAD

**Issue by andymsuk** [bbc/bbc-a11y#150]
## Summary
Frequently getting `TypeError: Cannot read property '_setChildrenPayload'` when running against multiple pages.

## Expected Behavior

No unexpected console errors.

## Current Behavior

~~~
[20043:0118/095114:ERROR:CONSOLE(1531)] "TypeError: Cannot read property '_setChildrenPayload' of undefined TypeError: Cannot read property '_setChildrenPayload' of undefined
    at Object._setChildNodes (chrome-devtools://devtools/bundled/inspector.js:5554:46)
    at Object.setChildNodes (chrome-devtools://devtools/bundled/inspector.js:5646:17)
    at Object.dispatch (chrome-devtools://devtools/bundled/inspector.js:4363:63)
    at Object.dispatch (chrome-devtools://devtools/bundled/inspector.js:4303:31)
    at Object._dispatchMessage (chrome-devtools://devtools/bundled/inspector.js:10293:7)
    at Object.dispatchEventToListeners (chrome-devtools://devtools/bundled/inspector.js:770:185)
    at innerDispatch (chrome-devtools://devtools/bundled/inspector.js:1531:58)
    at Object._dispatch (chrome-devtools://devtools/bundled/inspector.js:1530:1)
    at Object._dispatchOnInspectorFrontendAPI (<anonymous>:62:21)
    at Object.dispatchMessage (<anonymous>:147:14)", source: chrome-devtools://devtools/bundled/inspector.js (1531)
~~~

## Steps to Reproduce (for bugs)

1. Follow readme for using bbc-a11y
2. Setup `bbca11y.js` to have multiple pages, e.g.:
```
page("http://bbc.co.uk/iplayer")
page("http://www.bbc.co.uk/iplayer/categories/cbbc/highlights")
```
3. Run bbc-a11y: `./node_modules/.bin/bbc-a11y`

## Your Environment

* Version used: master
* Operating System and version: OSX 10.10.5

**Comment by joshski** [comment]
Hmm, I'm not getting this on OSX 10.12.2 (Sierra)

Can anybody else test this?

**Comment by joshski** [comment]
Actually I think I know what this is. Chromium outputs lots of junk out of stderr, which are generally safe to ignore. Other tools like (my own) cucumber-electron hide junk like the stuff you're seeing here, because it really is just chromium diagnostics and doesn't affect the running of a11y tests. So we need to mute noise like this:

https://github.com/cucumber/cucumber-electron/blob/23163afd918cc062f7f960e60219c644872bb287/bin/cucumber-electron.js#L31
