### ISSUE TITLE
Electron needs updating to support Apple M1 devices using Node 16

### ISSUE THREAD

**Issue by andymsuk** [bbc/bbc-a11y#345]
## Summary

Electron needs updating to support Apple M1 devices with Node 16

## Expected Behaviour
bbc-a11y can be installed with npm successfully on an Apple M1 device

## Current Behaviour
npm install fails with `Error: Failed to find Electron v2.0.18 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip`

## Your Environment

* Version used: Latest
* Operating System and version: macOS 12.2
* Node 16

**Comment by nicholasgriffintn** [comment]
I was just looking at this, it seems that the package.json is very out of date.

It might take quite a few updates to get this fully working with a new version of electron and we may have to reduce compatibility with older systems, so it would be a major version change, it appears that `@cucumber/electron` only supports version 12 or 14 of electron as well, so we're unable to go to the latest one.

**Comment by nicholasgriffintn** [comment]
This should be re-opened as it's still an issue with the library.

**Comment by LukeBBC** [comment]
Hi Team,

We're getting an error using our [a11y-test-web](https://github.com/bbc/a11y-tests-web) repo, whereby we need a version of electron that supports arm64. 

Could you please help support this?

Please see the full error below:

```
npm error Downloading electron-v2.0.18-darwin-arm64.zip
npm error [>                                            ] 0.0% (0 B/s)
npm error ^[[1000D^[[0K^[[1A^[[1000D^[[0K^[[1A^[[1000D^[[0KDownloading electron-v2.0.18-darwin-arm64.zip
npm error Error: GET https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip returned 404
npm error (node:13488) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
npm error (Use `node --trace-deprecation ...` to show where the warning was created)
npm error /Users/parkel02/Repos/a11y-tests-web/node_modules/bbc-a11y/node_modules/electron/install.js:54
npm error   throw err
npm error   ^
npm error
npm error Error: Failed to find Electron v2.0.18 for darwin-arm64 at https://github.com/electron/electron/releases/download/v2.0.18/electron-v2.0.18-darwin-arm64.zip
npm error     at Request.<anonymous> (/Users/parkel02/Repos/a11y-tests-web/node_modules/nugget/index.js:197:61)
npm error     at Request.emit (node:events:519:28)
npm error     at Request.onRequestResponse (/Users/parkel02/Repos/a11y-tests-web/node_modules/request/request.js:1059:10)
npm error     at ClientRequest.emit (node:events:519:28)
npm error     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:704:27)
npm error     at HTTPParser.parserOnHeadersComplete (node:_http_common:118:17)
npm error     at TLSSocket.socketOnData (node:_http_client:546:22)
npm error     at TLSSocket.emit (node:events:519:28)
npm error     at addChunk (node:internal/streams/readable:561:12)
npm error     at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
npm error
npm error Node.js v22.9.0
npm error A complete log of this run can be found in: /Users/parkel02/.npm/_logs/2025-03-12T14_03_58_230Z-debug-0.log
```

**Comment by nicholasgriffintn** [comment]
I've done some work to renew pervious work that will get it to electron 13: https://github.com/bbc/bbc-a11y/pull/375

I'm having problems with the headings tests not working with iframes, presumably due to some sort of chrome change, I'm still working it out.

**Comment by nicholasgriffintn** [comment]
This should be fixed in v3, it hasn't been released yet but it hopefully should be soon (ish).

We've upgraded to Electron 13.

I am going to look at if we can go further than that version next though in v3, if we can't easily, it'll stay at v13.

To note, as of v3, bbc-a11y will be published under the package name `@bbc/a11y` instead this is to bring it under the BBC org.
