### ISSUE TITLE
PhantomJS has crashed

### ISSUE THREAD

**Issue by greenc05** [bbc/bbc-a11y#97]
When running the tool I keep getting the following error when running the tool through a list of urls in the config file, is this something we should be concerned about or maybe it's just my set up and I just need to run it a few times until it behaves?

```
PhantomJS has crashed. Please read the crash reporting guide at https://github.com/ariya/phantomjs/wiki/Crash-Reporting and file a bug report at https://github.com/ariya/phantomjs/issues/new with the crash dump file attached: /tmp/21621846-E11A-4306-BB9D-E4B46C67B9E4.dmp
/Users/greenc05/.gem/ruby/2.0.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/server.rb:33:in `send': PhantomJS client died while processing {"name":"visit","args":["http://pal.sandbox.dev.bbc.co.uk/news/uk-england-london-32395047"]} (Capybara::Poltergeist::DeadClient)
	from /Users/greenc05/.gem/ruby/2.0.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:316:in `command'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/browser.rb:31:in `visit'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/poltergeist-1.6.0/lib/capybara/poltergeist/driver.rb:95:in `visit'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/capybara-2.4.4/lib/capybara/session.rb:227:in `visit'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/bbc-a11y-0.1.2/lib/bbc/a11y/linter.rb:8:in `lint'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/bbc-a11y-0.1.2/lib/bbc/a11y/runner.rb:34:in `check_standards_for'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/bbc-a11y-0.1.2/lib/bbc/a11y/runner.rb:23:in `block in run'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/bbc-a11y-0.1.2/lib/bbc/a11y/runner.rb:22:in `each'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/bbc-a11y-0.1.2/lib/bbc/a11y/runner.rb:22:in `run'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/bbc-a11y-0.1.2/lib/bbc/a11y/cli.rb:18:in `call'
	from /Users/greenc05/.gem/ruby/2.0.0/gems/bbc-a11y-0.1.2/bin/a11y:6:in `<top (required)>'
	from /Users/greenc05/.gem/ruby/2.0.0/bin/a11y:23:in `load'
	from /Users/greenc05/.gem/ruby/2.0.0/bin/a11y:23:in `<main>'
```

**Comment by joshski** [comment]
Hi @greenc05 -- I'm not seeing that error, but I probably haven't tested against so many URLs as you have. Are you using Windows?

I'd say, if it happens against the same URLs every time, then we should try to reproduce it and work around it. If it happens randomly, perhaps we can't do much about it.

FWIW there is a troubleshooting guide: http://phantomjs.org/crash-reporting.html

**Comment by greenc05** [comment]
@joshski Nope using a Mac, we have lot of urls in News/World Service with 28 websites...

I will add more details to this issue if it keeps happening...

**Comment by joshski** [comment]
Closing this until we can reproduce consistently.
